import = [
    "~/.config/alacritty/themes/gruvbox_material_hard_dark.toml"
]

[window]
padding = { x = 8, y = 8 }
opacity = 0.93 

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Medium" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }

